"""
Document Intelligence API - file upload, document list, and PDF export endpoints.
POST /v1/document-intelligence/{tool_id}/upload
GET  /v1/document-intelligence/{tool_id}/documents
GET  /v1/document-intelligence/{tool_id}/documents/{document_id}/pdf
"""
import html as html_lib
import io
from datetime import UTC, datetime
from typing import Annotated

import fitz
from fastapi import APIRouter, Depends, HTTPException, UploadFile, status
from fastapi.responses import StreamingResponse
from prisma import Prisma
from pydantic import BaseModel

from app.core.db import get_db_dep
from app.core.logging import get_logger
from app.core.responses import standard_response
from app.core.security import RequireOrgAuth
from app.queue.pool import get_queue_pool
from app.tools.document_intelligence import (
    _ALLOWED_CONTENT_TYPES,
    _MAX_FILE_BYTES,
    _generate_thumbnail,
)

logger = get_logger(__name__)
router = APIRouter(prefix="/document-intelligence", tags=["document-intelligence"])


class ImportRequest(BaseModel):
    file_ids: list[str] | None = None

_DECISION_LABELS = {
    "auto_approved": "Auto-approved",
    "approval_required": "Needs review",
    "classification_failed": "Unreadable",
    "blocked": "Blocked",
    "analysed": "Analysed",
}


def _generate_analysis_pdf(doc) -> bytes:
    """Build a structured PDF analysis report from a completed Document record."""
    extracted: dict = doc.extracted_json or {}

    def esc(v: object) -> str:
        return html_lib.escape(str(v) if v is not None else "")

    def ul(items: list, color: str = "#2c2c2c") -> str:
        if not items:
            return ""
        lis = "".join(f'<li style="color:{color}">{esc(item)}</li>' for item in items)
        return f"<ul>{lis}</ul>"

    summary = esc(extracted.get("summary", ""))
    parties   = [str(p) for p in (extracted.get("parties")      or [])]
    key_dates = [str(d) for d in (extracted.get("key_dates")    or [])]
    risks        = [str(r) for r in (extracted.get("risks")       or [])]
    loopholes    = [str(lo) for lo in (extracted.get("loopholes") or [])]
    improvements = [str(i)  for i  in (extracted.get("improvements") or [])]
    subtype = str(extracted.get("document_subtype") or "").replace("_", " ").title()

    filename      = esc(doc.filename or "Untitled")
    analysed_at   = doc.created_at.strftime("%d %b %Y, %H:%M") if doc.created_at else "-"
    confidence_pct = f"{int((doc.confidence or 0) * 100)}%" if doc.confidence is not None else "-"
    decision_label = esc(_DECISION_LABELS.get(doc.decision or "", doc.decision or "-"))

    meta_lines = [
        f"<p class='meta'><b>File:</b> {filename}</p>",
        f"<p class='meta'><b>Analysed:</b> {esc(analysed_at)}</p>",
        f"<p class='meta'><b>Confidence:</b> {esc(confidence_pct)}</p>",
        f"<p class='meta'><b>Decision:</b> {decision_label}</p>",
    ]
    if subtype:
        meta_lines.append(f"<p class='meta'><b>Type:</b> {esc(subtype)}</p>")
    if doc.rule_triggered:
        meta_lines.append(
            f"<p class='meta'><b>Flagged by:</b> "
            f"<span style='color:#b05000'>{esc(doc.rule_triggered)}</span></p>"
        )

    sections = []
    if summary:
        sections.append(f"<h2>Summary</h2><p>{summary}</p>")
    if parties:
        sections.append(f"<h2>Parties</h2>{ul(parties)}")
    if key_dates:
        sections.append(f"<h2>Key Dates</h2>{ul(key_dates)}")
    if risks:
        sections.append(f"<h2>Risks ({len(risks)})</h2>{ul(risks, '#a00020')}")
    if loopholes:
        sections.append(f"<h2>Loopholes ({len(loopholes)})</h2>{ul(loopholes, '#b05000')}")
    if improvements:
        sections.append(f"<h2>Improvements ({len(improvements)})</h2>{ul(improvements)}")

    generated_at = datetime.now(UTC).strftime("%d %b %Y %H:%M UTC")

    body_html = (
        "<h1>Document Analysis Report</h1>"
        + "".join(meta_lines)
        + "".join(sections)
        + f"<p class='footer'>Generated by Clendan · {esc(generated_at)}</p>"
    )

    css = """
body  { font-family: Helvetica; font-size: 9pt; color: #1a1a1a; }
h1    { font-size: 14pt; color: #0d1117; margin: 0 0 8pt 0; }
h2    { font-size: 10pt; color: #0d1117; margin: 12pt 0 4pt 0; }
p     { margin: 2pt 0; line-height: 1.4; }
p.meta   { font-size: 8.5pt; color: #444; margin: 1pt 0; }
p.footer { font-size: 7.5pt; color: #999; margin-top: 14pt; }
ul    { margin: 3pt 0 3pt 12pt; padding: 0; }
li    { margin: 2pt 0; line-height: 1.4; }
"""

    story = fitz.Story(html=body_html, user_css=css)
    buf = io.BytesIO()
    writer = fitz.DocumentWriter(buf)
    mediabox = fitz.Rect(0, 0, 595, 842)   # A4
    where    = fitz.Rect(50, 50, 545, 792)  # 50 pt margins

    more = True
    while more:
        device = writer.begin_page(mediabox)
        more, _ = story.place(where)
        story.draw(device)
        writer.end_page()

    writer.close()
    return buf.getvalue()


def _serialize_document(doc) -> dict:
    return {
        "id": doc.id,
        "document_type": doc.document_type,
        "filename": doc.filename,
        "content_type": doc.content_type,
        "file_size_bytes": doc.file_size_bytes,
        "uploaded_by": doc.uploaded_by,
        "status": doc.status,
        "decision": doc.decision,
        "confidence": doc.confidence,
        "rule_triggered": doc.rule_triggered,
        "reason": doc.reason,
        "flags_json": doc.flags_json,
        "extracted_json": doc.extracted_json,
        "thumbnail_b64": doc.thumbnail_b64,
        "created_at": doc.created_at.isoformat() if doc.created_at else None,
    }


@router.post("/{tool_id}/upload")
async def upload_document(
    tool_id: str,
    file: UploadFile,
    current_user: RequireOrgAuth,
    db: Annotated[Prisma, Depends(get_db_dep)],
) -> dict:
    """
    Accept a document upload, generate a thumbnail, create a Document record,
    and enqueue the document_intelligence job for async processing.
    Claude analyses the document and produces structured output - summary, risks, loopholes, improvements.
    """
    tenant_id = current_user.tenant_id
    logger.debug("doc_upload_start", extra={"tenant_id": tenant_id, "tool_id": tool_id, "file_name": file.filename, "content_type": file.content_type})

    content_type = file.content_type or "application/pdf"
    if content_type not in _ALLOWED_CONTENT_TYPES:
        logger.debug("doc_upload_unsupported_content_type", extra={"content_type": content_type})
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail="Unsupported file type. Allowed: PDF, Word (.docx), PNG, JPG, WebP",
        )

    file_bytes = await file.read()
    logger.debug("doc_upload_file_read", extra={"size_bytes": len(file_bytes), "content_type": content_type})

    if len(file_bytes) > _MAX_FILE_BYTES:
        logger.debug("doc_upload_file_too_large", extra={"size_bytes": len(file_bytes)})
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail="File exceeds 10 MB limit",
        )
    if not file_bytes:
        logger.debug("doc_upload_empty_file")
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Empty file")

    tool = await db.tool.find_unique(where={"id": tool_id})
    if not tool or tool.tenant_id != tenant_id:
        logger.debug("doc_upload_tool_not_found", extra={"tool_id": tool_id})
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Tool not found")
    if tool.type != "document_intelligence":
        logger.debug("doc_upload_wrong_tool_type", extra={"tool_type": tool.type})
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Tool is not of type document_intelligence",
        )
    logger.debug("doc_upload_tool_verified", extra={"tool_id": tool_id})

    thumbnail_b64 = _generate_thumbnail(file_bytes, content_type)
    logger.debug("doc_upload_thumbnail_generated", extra={"has_thumbnail": thumbnail_b64 is not None})

    doc_record = await db.document.create(data={
        "tenant_id": tenant_id,
        "tool_id": tool_id,
        "document_type": "pending",
        "filename": file.filename,
        "content_type": content_type,
        "file_size_bytes": len(file_bytes),
        "uploaded_by": current_user.email,
        "status": "processing",
        "thumbnail_b64": thumbnail_b64,
    })
    logger.debug("doc_upload_record_created", extra={"document_id": doc_record.id})

    idempotency_key = f"doc-upload:{doc_record.id}"
    execution = await db.execution.create(data={
        "tenant_id": tenant_id,
        "tool_id": tool_id,
        "input_ref": idempotency_key,
        "decision": "pending",
        "confidence": 0.0,
        "status": "queued",
        "triggered_by_email": current_user.email,
    })
    logger.debug("doc_upload_execution_created", extra={"execution_id": execution.id})

    await db.document.update(
        where={"id": doc_record.id},
        data={"execution_id": execution.id},
    )
    logger.debug("doc_upload_execution_linked", extra={"document_id": doc_record.id, "execution_id": execution.id})

    pool = await get_queue_pool()
    await pool.enqueue_job(
        "run_document_intelligence_job",
        execution_id=execution.id,
        tenant_id=tenant_id,
        tool_id=tool_id,
        file_bytes=file_bytes,
        content_type=content_type,
        document_id=doc_record.id,
    )
    logger.info(
        "document_upload_queued",
        extra={
            "tenant_id": tenant_id,
            "tool_id": tool_id,
            "document_id": doc_record.id,
            "execution_id": execution.id,
            "file_name": file.filename,
            "size_bytes": len(file_bytes),
        },
    )

    return standard_response(data={
        "document_id": doc_record.id,
        "execution_id": execution.id,
        "status": "processing",
        "thumbnail_b64": thumbnail_b64,
    })


@router.post("/{tool_id}/documents/{document_id}/abort")
async def abort_document(
    tool_id: str,
    document_id: str,
    current_user: RequireOrgAuth,
    db: Annotated[Prisma, Depends(get_db_dep)],
) -> dict:
    """Mark a processing document as aborted. Does not cancel the arq job if already running,
    but the job's result will land on a record already marked failed."""
    tenant_id = current_user.tenant_id

    doc = await db.document.find_unique(where={"id": document_id})
    if not doc or doc.tenant_id != tenant_id or doc.tool_id != tool_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")
    await db.document.delete(where={"id": document_id})

    logger.info("document_deleted", extra={"tenant_id": tenant_id, "document_id": document_id, "prior_status": doc.status})
    return standard_response(data={"document_id": document_id, "deleted": True})


@router.get("/{tool_id}/documents/{document_id}/pdf")
async def export_document_pdf(
    tool_id: str,
    document_id: str,
    current_user: RequireOrgAuth,
    db: Annotated[Prisma, Depends(get_db_dep)],
) -> StreamingResponse:
    """Generate and stream a PDF analysis report for a completed document."""
    tenant_id = current_user.tenant_id

    doc = await db.document.find_unique(where={"id": document_id})
    if not doc or doc.tenant_id != tenant_id or doc.tool_id != tool_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")
    if doc.status != "completed" or not doc.extracted_json:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Analysis not yet complete")

    try:
        pdf_bytes = _generate_analysis_pdf(doc)
    except Exception as exc:
        logger.error("pdf_generation_failed", extra={"document_id": document_id, "error": str(exc)})
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="PDF generation failed")

    base = (doc.filename or document_id).rsplit(".", 1)[0]
    filename = f"{base}_analysis.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.post("/{tool_id}/documents/{document_id}/export/google-drive")
async def export_to_google_drive(
    tool_id: str,
    document_id: str,
    current_user: RequireOrgAuth,
    db: Annotated[Prisma, Depends(get_db_dep)],
) -> dict:
    """Generate analysis PDF and upload it to the tenant's connected Google Drive."""
    from app.integrations.encryption import decrypt_credentials
    from app.integrations.google import client as _google

    tenant_id = current_user.tenant_id

    doc = await db.document.find_unique(where={"id": document_id})
    if not doc or doc.tenant_id != tenant_id or doc.tool_id != tool_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")
    if doc.status != "completed" or not doc.extracted_json:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Analysis not yet complete")

    integration = await db.integration.find_first(
        where={"tenant_id": tenant_id, "type": "google_drive", "status": "connected"}
    )
    if not integration:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="No connected Google Drive integration")

    try:
        creds = decrypt_credentials(integration.encrypted_credentials, tenant_id)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Credential decryption failed")

    try:
        pdf_bytes = _generate_analysis_pdf(doc)
    except Exception as exc:
        logger.error("pdf_generation_failed", extra={"document_id": document_id, "error": str(exc)})
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="PDF generation failed")

    base = (doc.filename or document_id).rsplit(".", 1)[0]
    filename = f"{base}_analysis.pdf"

    try:
        file_id = await _google.upload_file_to_drive(creds.get("access_token", ""), pdf_bytes, filename)
    except Exception as exc:
        logger.error("drive_export_failed", extra={"document_id": document_id, "error": str(exc)})
        raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail="Upload to Google Drive failed")

    logger.info("drive_export_ok", extra={"document_id": document_id, "file_id": file_id})
    return standard_response(data={"file_id": file_id, "filename": filename, "destination": "google_drive"})


@router.post("/{tool_id}/documents/{document_id}/export/dropbox")
async def export_to_dropbox(
    tool_id: str,
    document_id: str,
    current_user: RequireOrgAuth,
    db: Annotated[Prisma, Depends(get_db_dep)],
) -> dict:
    """Generate analysis PDF and upload it to the tenant's connected Dropbox under /Clendan/."""
    from app.integrations.encryption import decrypt_credentials
    from app.integrations.dropbox import client as _dropbox

    tenant_id = current_user.tenant_id

    doc = await db.document.find_unique(where={"id": document_id})
    if not doc or doc.tenant_id != tenant_id or doc.tool_id != tool_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")
    if doc.status != "completed" or not doc.extracted_json:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Analysis not yet complete")

    integration = await db.integration.find_first(
        where={"tenant_id": tenant_id, "type": "dropbox", "status": "connected"}
    )
    if not integration:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="No connected Dropbox integration")

    try:
        creds = decrypt_credentials(integration.encrypted_credentials, tenant_id)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Credential decryption failed")

    try:
        pdf_bytes = _generate_analysis_pdf(doc)
    except Exception as exc:
        logger.error("pdf_generation_failed", extra={"document_id": document_id, "error": str(exc)})
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="PDF generation failed")

    base = (doc.filename or document_id).rsplit(".", 1)[0]
    filename = f"{base}_analysis.pdf"

    try:
        result = await _dropbox.upload_file(creds.get("access_token", ""), pdf_bytes, filename)
    except Exception as exc:
        logger.error("dropbox_export_failed", extra={"document_id": document_id, "error": str(exc)})
        raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail="Upload to Dropbox failed")

    logger.info("dropbox_export_ok", extra={"document_id": document_id, "path": result.get("path_display", "")})
    return standard_response(data={"path": result.get("path_display", ""), "filename": filename, "destination": "dropbox"})


@router.post("/{tool_id}/documents/{document_id}/export/onedrive")
async def export_to_onedrive(
    tool_id: str,
    document_id: str,
    current_user: RequireOrgAuth,
    db: Annotated[Prisma, Depends(get_db_dep)],
) -> dict:
    """Generate analysis PDF and upload it to the tenant's connected OneDrive under /Clendan/."""
    from app.integrations.encryption import decrypt_credentials
    from app.integrations.onedrive import client as _onedrive

    tenant_id = current_user.tenant_id

    doc = await db.document.find_unique(where={"id": document_id})
    if not doc or doc.tenant_id != tenant_id or doc.tool_id != tool_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")
    if doc.status != "completed" or not doc.extracted_json:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Analysis not yet complete")

    integration = await db.integration.find_first(
        where={"tenant_id": tenant_id, "type": "onedrive", "status": "connected"}
    )
    if not integration:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="No connected OneDrive integration")

    try:
        creds = decrypt_credentials(integration.encrypted_credentials, tenant_id)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Credential decryption failed")

    try:
        pdf_bytes = _generate_analysis_pdf(doc)
    except Exception as exc:
        logger.error("pdf_generation_failed", extra={"document_id": document_id, "error": str(exc)})
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="PDF generation failed")

    base = (doc.filename or document_id).rsplit(".", 1)[0]
    filename = f"{base}_analysis.pdf"

    try:
        item = await _onedrive.upload_file(creds.get("access_token", ""), pdf_bytes, filename)
    except Exception as exc:
        logger.error("onedrive_export_failed", extra={"document_id": document_id, "error": str(exc)})
        raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail="Upload to OneDrive failed")

    logger.info("onedrive_export_ok", extra={"document_id": document_id, "item_id": item.get("id", "")})
    return standard_response(data={"item_id": item.get("id", ""), "filename": filename, "destination": "onedrive"})


@router.get("/{tool_id}/browse/{source}")
async def browse_integration_files(
    tool_id: str,
    source: str,
    current_user: RequireOrgAuth,
    db: Annotated[Prisma, Depends(get_db_dep)],
) -> dict:
    """List PDF files available in a connected integration without importing them."""
    from app.integrations.encryption import decrypt_credentials

    SUPPORTED = {"google_drive", "dropbox", "onedrive"}
    if source not in SUPPORTED:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Unsupported source")

    tenant_id = current_user.tenant_id

    tool = await db.tool.find_unique(where={"id": tool_id})
    if not tool or tool.tenant_id != tenant_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Tool not found")

    integration = await db.integration.find_first(
        where={"tenant_id": tenant_id, "type": source, "status": "connected"}
    )
    if not integration:
        label = source.replace("_", " ").title()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"No connected {label} integration. Connect it in Integrations first.",
        )

    try:
        creds = decrypt_credentials(integration.encrypted_credentials, tenant_id)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Credential decryption failed")

    access_token = creds.get("access_token", "")

    try:
        if source == "google_drive":
            from app.integrations.google import client as _google
            raw_files = await _google.list_pdf_files(access_token)
        elif source == "dropbox":
            from app.integrations.dropbox import client as _dropbox
            raw_files = await _dropbox.list_pdf_files(access_token)
        else:
            from app.integrations.onedrive import client as _onedrive
            raw_files = await _onedrive.list_pdf_files(access_token)
    except Exception as exc:
        logger.error("browse_list_failed source=%s error=%s", source, str(exc))
        raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail=f"Failed to list files from {source}")

    PREFIX = {"google_drive": "drive", "dropbox": "dropbox", "onedrive": "onedrive"}
    prefix = PREFIX[source]

    files = []
    for f in raw_files:
        file_id = f.get("id", "")
        if not file_id:
            continue
        idempotency_key = f"{prefix}:document:{file_id}"
        existing = await db.execution.find_first(
            where={"input_ref": idempotency_key, "tenant_id": tenant_id}
        )
        raw_size = f.get("size")
        files.append({
            "id": file_id,
            "name": f.get("name", ""),
            "size": int(raw_size) if raw_size is not None else None,
            "modified": f.get("modifiedTime"),  # populated by Google Drive; None for others
            "already_imported": existing is not None,
        })

    return standard_response(data={"files": files, "source": source})


@router.post("/{tool_id}/import/{source}")
async def import_from_integration(
    tool_id: str,
    source: str,
    body: ImportRequest,
    current_user: RequireOrgAuth,
    db: Annotated[Prisma, Depends(get_db_dep)],
) -> dict:
    """
    Trigger an ad-hoc import from Google Drive, Dropbox, or OneDrive.
    Lists new PDF files from the connected integration and enqueues Document Intelligence
    analysis for each one not yet processed.
    """
    import base64 as _b64

    SUPPORTED = {"google_drive", "dropbox", "onedrive"}
    if source not in SUPPORTED:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unsupported source. Must be one of: {', '.join(sorted(SUPPORTED))}",
        )

    tenant_id = current_user.tenant_id

    tool = await db.tool.find_unique(where={"id": tool_id})
    if not tool or tool.tenant_id != tenant_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Tool not found")

    from app.integrations.encryption import decrypt_credentials

    integration = await db.integration.find_first(
        where={"tenant_id": tenant_id, "type": source, "status": "connected"}
    )
    if not integration:
        label = source.replace("_", " ").title()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"No connected {label} integration. Connect it in Integrations first.",
        )

    try:
        creds = decrypt_credentials(integration.encrypted_credentials, tenant_id)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Credential decryption failed")

    access_token = creds.get("access_token", "")

    try:
        if source == "google_drive":
            from app.integrations.google import client as _google
            files = await _google.list_pdf_files(access_token)
        elif source == "dropbox":
            from app.integrations.dropbox import client as _dropbox
            files = await _dropbox.list_pdf_files(access_token)
        else:
            from app.integrations.onedrive import client as _onedrive
            files = await _onedrive.list_pdf_files(access_token)
    except Exception as exc:
        logger.error("import_list_failed source=%s error=%s", source, str(exc))
        raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail=f"Failed to list files from {source}")

    from app.events import enqueue_event

    queued = 0
    skipped = 0

    allowed_ids = set(body.file_ids) if body.file_ids is not None else None

    for f in files:
        file_id = f.get("id", "")
        if not file_id:
            continue

        if allowed_ids is not None and file_id not in allowed_ids:
            continue

        PREFIX = {"google_drive": "drive", "dropbox": "dropbox", "onedrive": "onedrive"}
        idempotency_key = f"{PREFIX[source]}:document:{file_id}"

        existing = await db.execution.find_first(
            where={"input_ref": idempotency_key, "tenant_id": tenant_id}
        )
        if existing:
            skipped += 1
            continue

        try:
            if source == "google_drive":
                file_bytes = await _google.download_drive_file_bytes(access_token, file_id)
            elif source == "dropbox":
                path = f.get("path_lower", "")
                file_bytes = await _dropbox.download_file(access_token, path)
            else:
                file_bytes = await _onedrive.download_file(access_token, file_id)
        except Exception as exc:
            logger.warning("import_download_failed source=%s file_id=%s: %s", source, file_id, str(exc))
            skipped += 1
            continue

        if len(file_bytes) > _MAX_FILE_BYTES:
            logger.warning("import_file_too_large source=%s file_id=%s size=%d", source, file_id, len(file_bytes))
            skipped += 1
            continue

        try:
            await enqueue_event(
                tenant_id=tenant_id,
                event_type="document_received",
                payload={
                    "source": source,
                    "integration_id": integration.id,
                    "file_id": file_id,
                    "filename": f.get("name", ""),
                    "file_bytes": _b64.b64encode(file_bytes).decode(),
                    "content_type": "application/pdf",
                },
                idempotency_key=idempotency_key,
                db=db,
                triggered_by_email=current_user.email,
            )
            queued += 1
        except Exception as exc:
            logger.error("import_enqueue_failed source=%s file_id=%s: %s", source, file_id, str(exc))
            skipped += 1

    logger.info(
        "import_complete",
        extra={"tenant_id": tenant_id, "source": source, "queued": queued, "skipped": skipped},
    )
    return standard_response(data={"queued": queued, "skipped": skipped, "source": source})


@router.get("/{tool_id}/documents")
async def list_documents(
    tool_id: str,
    current_user: RequireOrgAuth,
    db: Annotated[Prisma, Depends(get_db_dep)],
    limit: int = 50,
    offset: int = 0,
) -> dict:
    """Return all documents processed by this tool, newest first."""
    tenant_id = current_user.tenant_id

    tool = await db.tool.find_unique(where={"id": tool_id})
    if not tool or tool.tenant_id != tenant_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Tool not found")

    documents = await db.document.find_many(
        where={"tenant_id": tenant_id, "tool_id": tool_id},
        order={"created_at": "desc"},
        take=min(limit, 100),
        skip=offset,
    )

    total = await db.document.count(
        where={"tenant_id": tenant_id, "tool_id": tool_id}
    )

    return standard_response(data={
        "documents": [_serialize_document(doc) for doc in documents],
        "total": total,
        "limit": limit,
        "offset": offset,
    })
