import type React from "react";

const FONT = "'IBM Plex Mono', 'Courier New', monospace";

const COLOR = {
  bg: "#0a0a0a",
  surface: "#111111",
  border: "#1a2a1a",
  borderSubtle: "#1e1e1e",
  text: "#e8f0e8",
  textSecondary: "#a0b8a0",
  textMuted: "#6e8c6e",
  green: "#00C853",
  danger: "#ff4d6d",
  info: "#00a8cc",
};

export const styles: Record<string, React.CSSProperties> = {
  // Auth
  authContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "32px 16px",
    minHeight: "100vh",
    background: COLOR.bg,
    fontFamily: FONT,
  },
  logoMark: {
    width: 48,
    height: 48,
    border: `2px solid ${COLOR.green}`,
    borderRadius: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: COLOR.green,
    fontSize: 22,
    fontWeight: 800,
    marginBottom: 12,
    lineHeight: 1,
    paddingTop: 2,
  },
  authTitle: {
    fontSize: 20,
    fontWeight: 800,
    color: COLOR.text,
    margin: "0 0 4px",
    letterSpacing: 4,
    fontFamily: FONT,
  },
  authSubtitle: {
    fontSize: 11,
    color: COLOR.textMuted,
    margin: "0 0 32px",
    fontFamily: FONT,
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    width: "100%",
    maxWidth: 300,
  },

  // App shell
  appShell: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    background: COLOR.bg,
    fontFamily: FONT,
    color: COLOR.text,
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "12px 16px",
    borderBottom: `1px solid ${COLOR.border}`,
    background: COLOR.surface,
  },
  headerLogoMark: {
    width: 28,
    height: 28,
    border: `1.5px solid ${COLOR.green}`,
    borderRadius: 3,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: COLOR.green,
    fontSize: 13,
    fontWeight: 800,
    flexShrink: 0,
    paddingTop: 1,
  },
  headerWordmark: {
    fontSize: 13,
    fontWeight: 700,
    color: COLOR.text,
    letterSpacing: 3,
    flex: 1,
    fontFamily: FONT,
  },
  headerKeyHint: {
    fontSize: 10,
    color: COLOR.textMuted,
    fontFamily: FONT,
  },

  // Content
  content: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    padding: "16px 16px 0",
    flex: 1,
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginBottom: 16,
  },
  dashboardSection: {
    marginTop: "auto",
    paddingBottom: 16,
  },
  divider: {
    height: 1,
    background: COLOR.border,
    margin: "0 0 16px",
  },

  // Form elements
  label: {
    fontSize: 10,
    fontWeight: 500,
    color: COLOR.textMuted,
    letterSpacing: 1.5,
    fontFamily: FONT,
    margin: 0,
  },
  input: {
    background: COLOR.bg,
    border: `1px solid ${COLOR.border}`,
    borderRadius: 4,
    color: COLOR.text,
    fontFamily: FONT,
    fontSize: 12,
    padding: "8px 10px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  select: {
    background: COLOR.surface,
    border: `1px solid ${COLOR.border}`,
    borderRadius: 4,
    color: COLOR.text,
    fontFamily: FONT,
    fontSize: 12,
    padding: "8px 10px",
    outline: "none",
    width: "100%",
    cursor: "pointer",
    appearance: "none",
  },

  // Buttons
  primaryButton: {
    background: COLOR.green,
    color: "#000000",
    border: "none",
    borderRadius: 4,
    fontFamily: FONT,
    fontSize: 12,
    fontWeight: 600,
    padding: "9px 16px",
    cursor: "pointer",
    width: "100%",
    letterSpacing: 0.5,
  },
  secondaryButton: {
    background: "transparent",
    border: `1px solid ${COLOR.border}`,
    borderRadius: 4,
    color: COLOR.text,
    fontFamily: FONT,
    fontSize: 11,
    padding: "6px 12px",
    cursor: "pointer",
  },
  copyButton: {
    background: "transparent",
    border: `1px solid ${COLOR.border}`,
    borderRadius: 3,
    color: COLOR.textMuted,
    fontFamily: FONT,
    fontSize: 10,
    padding: "2px 8px",
    cursor: "pointer",
  },
  dismissButton: {
    background: "transparent",
    border: "none",
    color: COLOR.textMuted,
    fontFamily: FONT,
    fontSize: 14,
    cursor: "pointer",
    padding: 0,
    lineHeight: 1,
  },

  // Range runner
  rangeRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: COLOR.surface,
    border: `1px solid ${COLOR.border}`,
    borderRadius: 4,
    padding: "6px 10px",
  },
  rangeAddress: {
    flex: 1,
    fontSize: 12,
    color: COLOR.textSecondary,
    fontFamily: FONT,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  // Results panel
  resultsCard: {
    background: COLOR.surface,
    border: `1px solid ${COLOR.border}`,
    borderRadius: 4,
    padding: 12,
    marginBottom: 16,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  resultsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  resultsSectionLabel: {
    fontSize: 10,
    fontWeight: 500,
    color: COLOR.textMuted,
    letterSpacing: 1.5,
    fontFamily: FONT,
  },
  statusBadge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "3px 8px",
    borderRadius: 3,
    fontSize: 11,
    fontWeight: 600,
    fontFamily: FONT,
    alignSelf: "flex-start",
  },
  resultRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  resultLabel: {
    fontSize: 11,
    color: COLOR.textMuted,
    fontFamily: FONT,
  },
  resultValue: {
    fontSize: 11,
    color: COLOR.text,
    fontFamily: FONT,
    textAlign: "right",
  },
  executionIdRow: {
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  executionId: {
    fontSize: 11,
    color: COLOR.textMuted,
    fontFamily: FONT,
  },
  idempotentNote: {
    fontSize: 10,
    color: COLOR.info,
    fontFamily: FONT,
  },
  dashboardLink: {
    fontSize: 11,
    color: COLOR.textSecondary,
    textDecoration: "none",
    fontFamily: FONT,
    marginTop: 4,
  },

  // Feedback text
  errorText: {
    fontSize: 11,
    color: COLOR.danger,
    margin: "4px 0 0",
    fontFamily: FONT,
  },
  successText: {
    fontSize: 11,
    color: COLOR.green,
    margin: "4px 0 0",
    fontFamily: FONT,
  },
  helpText: {
    fontSize: 11,
    color: COLOR.textMuted,
    margin: "24px 0 0",
    textAlign: "center",
    fontFamily: FONT,
  },
  link: {
    color: COLOR.textSecondary,
    textDecoration: "underline",
  },
  disconnectButton: {
    background: "transparent",
    border: "none",
    color: COLOR.textMuted,
    fontFamily: FONT,
    fontSize: 10,
    cursor: "pointer",
    padding: 0,
    textDecoration: "underline",
  },
};
