export interface ToolDef {
  slug: string
  type: string
  name: string
  desc: string
  capabilities: string[]
  howItWorks?: { step: string; label: string; desc: string }[]
}

export const TOOLS: ToolDef[] = [
  {
    slug: 'reconciliation',
    type: 'reconciliation',
    name: 'Reconciliation',
    desc: 'Match bank transactions against invoices. Detects unmatched items and flags anomalies.',
    capabilities: [
      'Match bank transactions against invoices within configurable tolerances',
      'Flag unmatched, flagged, and review-required items per run',
      'Export reconciliation results to CSV',
      'Configurable amount and date tolerance windows',
      'Stale open-item detection and alerting',
    ],
  },
  {
    slug: 'document-intelligence',
    type: 'document_intelligence',
    name: 'Document Intelligence',
    desc: 'Upload any business document. Clen reads it and produces a structured analysis — summary, risks, loopholes, key dates, and improvement suggestions.',
    capabilities: [
      'AI-generated summary of any business document in plain English',
      'Risk analysis — surfaces hidden obligations, liabilities, and ambiguous clauses',
      'Loophole detection — flags gaps that could be exploited or misinterpreted',
      'Improvement suggestions — missing protections, weak language, recommended additions',
      'Extracts parties, key dates, and document subtype automatically',
      'Supports PDF, Word (.docx), PNG, JPG, and WebP — up to 10 MB',
      'Export full analysis as structured JSON',
      'Every analysis written to the immutable audit log',
    ],
    howItWorks: [
      { step: '01', label: 'Upload',   desc: 'Drop or browse for a PDF, image, or Word document. Multiple files can be uploaded at once.' },
      { step: '02', label: 'Read',     desc: 'Claude reads the full document. Unreadable or blank files are flagged immediately with a reason.' },
      { step: '03', label: 'Analyse',  desc: 'Claude produces a structured analysis — summary, risks, loopholes, improvements, parties, and key dates.' },
      { step: '04', label: 'Audit',    desc: 'The full analysis and confidence score are written to the immutable audit log before the response is returned.' },
    ],
  },
  {
    slug: 'ai-accountant',
    type: 'ai_accountant',
    name: 'AI Accountant',
    desc: 'Automate journal entries, categorisation, month-end close, and payroll reconciliation.',
    capabilities: [
      'Automatic transaction categorisation with confidence scoring',
      'Human review queue for low-confidence categorisations',
      'Learns from manual corrections over time',
      'Strict chart-of-accounts mode enforcement',
      'Month-end close orchestration — task tracking, reconciliation sign-offs, bottleneck detection',
      'Payroll reconciliation against HR data with ghost employee detection',
      'Payroll journal entry posting with automated approval routing',
      'Batch processing for high-volume transaction periods',
      'Configurable model retraining frequency',
    ],
  },
  {
    slug: 'spend-control',
    type: 'spend_control',
    name: 'Spend Control',
    desc: 'Process bills, enforce spend policies, detect duplicates, and route payments for approval.',
    capabilities: [
      'Automated bill processing from all connected accounting sources',
      'Duplicate detection by contact and amount within configurable window',
      'Per-transaction, daily, and monthly spend limit enforcement',
      'Pre-approval routing for high-value bills and expenses',
      'Category spend limits — meals, hotel per-diem, cash advances',
      'Receipt requirement enforcement above configurable threshold',
      'Real-time policy violation flagging before payment',
      'Multi-source aggregation: FreshBooks, Xero, QuickBooks',
    ],
  },
  {
    slug: 'ar-collections',
    type: 'ar_collections',
    name: 'AR & Collections',
    desc: 'Monitor outstanding invoices, classify urgency, automate debtor follow-ups and escalation.',
    capabilities: [
      'Real-time outstanding and overdue invoice monitoring',
      'AI urgency classification across all connected accounting sources',
      'Tiered reminder cadence — day 3, 14, 45, 90',
      'Automated chase email drafting per debtor',
      'Automatic escalation to legal referral',
      'Late fee calculation and application',
      'Write-off blocking above configurable outstanding threshold',
      'Per-debtor communication rate limiting and contact frequency caps',
      'Multi-source aggregation: FreshBooks, Xero, QuickBooks',
    ],
  },
  {
    slug: 'risk-compliance',
    type: 'risk_compliance',
    name: 'Risk & Compliance',
    desc: 'Detect fraud, monitor regulatory compliance, and maintain audit-ready records year-round.',
    capabilities: [
      'Risk-score-based transaction blocking and review thresholds',
      'Velocity detection within configurable time windows',
      'CTR threshold monitoring and structuring detection',
      'SAR auto-file controls (configurable)',
      'KYC refresh scheduling — standard and high-risk cadences',
      'PEP screening on all counterparties',
      'GDPR data retention enforcement',
      'Year-round audit preparation — evidence pack maintenance, PBC list management',
      'Periodic model retraining for fraud drift detection',
    ],
  },
  {
    slug: 'treasury-cash',
    type: 'treasury_cash',
    name: 'Treasury & Cash',
    desc: 'Monitor cash positions, forecast liquidity, track FX exposure, and monitor budget vs. actuals.',
    capabilities: [
      'Multi-bank balance aggregation and cash position tracking',
      'Runway and operating balance alerting',
      '30, 60, and 90-day cash flow bucketing from live accounting data',
      'Configurable rolling cash flow forecast with AI narrative',
      'FX exposure monitoring and unhedged position alerts',
      'Budget vs. actuals variance tracking with automatic explanations',
      'Payroll reserve buffer enforcement',
      'Bank counterparty concentration limits',
      'Optional automated cash sweep execution',
    ],
  },
  {
    slug: 'revenue-recognition',
    type: 'revenue_recognition',
    name: 'Revenue Recognition',
    desc: 'Automate ASC 606 / IFRS 15 revenue recognition schedules.',
    capabilities: [
      'ASC 606 and IFRS 15 recognition schedule generation',
      'Point-in-time and over-time recognition methods',
      'Variable consideration constraint enforcement',
      'Daily or monthly recognition frequency',
      'Period lock enforcement for closed periods',
      'Expected value and most-likely-amount estimation',
    ],
  },
  {
    slug: 'credit-underwriting',
    type: 'credit_underwriting',
    name: 'Credit Underwriting',
    desc: 'Assess credit risk and generate underwriting decisions.',
    capabilities: [
      'Automated credit score and DTI ratio evaluation',
      'Auto-approve decisions above score threshold',
      'LTV ratio enforcement for secured lending',
      'Employment duration validation',
      'Maximum loan amount controls',
      'Automatic adverse action notice generation',
    ],
  },
  {
    slug: 'tax-compliance',
    type: 'tax_compliance',
    name: 'Tax Compliance',
    desc: 'Compute VAT position, detect missing tax codes, and flag filing risks.',
    capabilities: [
      'VAT collected and input VAT computation from live invoice and expense data',
      'Net VAT liability or reclaim position calculation',
      'Missing tax code detection across bills and expenses',
      'AI-generated filing risk summary and recommendations',
      'Approval routing when liability exceeds configurable threshold',
      'Multi-source aggregation: FreshBooks, Xero, QuickBooks',
    ],
  },
  {
    slug: 'financial-reporting',
    type: 'financial_reporting',
    name: 'Financial Reporting',
    desc: 'Auto-generate P&L, balance sheet, and cash flow statements from live accounting data.',
    capabilities: [
      'Profit & loss statement with gross margin and net profit analysis',
      'Balance sheet summary — assets, liabilities, and net asset position',
      'Cash flow statement from live bank and payment data',
      'AI-generated CFO-level narrative and anomaly detection',
      'Approval routing when anomalies or at-risk health indicators are detected',
      'Configurable lookback period (30, 60, or 90 days)',
      'Multi-source aggregation: Xero, QuickBooks, FreshBooks, bank connections',
    ],
  },
  {
    slug: 'payment-runs',
    type: 'payment_run',
    name: 'Payment Runs',
    desc: 'Automatically schedule approved supplier payments on a weekly cadence.',
    capabilities: [
      'Weekly automated payment run across all outstanding approved bills',
      'Auto-pay bills within configurable spend limit without manual intervention',
      'Approval routing for bills above the auto-pay threshold',
      'Duplicate and risk detection across the payment batch before scheduling',
      'Immutable PaymentRun record created per batch for full audit trail',
      'Configurable due-date window — only pays bills due within N days',
      'Blocked bills excluded automatically — no manual filtering required',
    ],
  },
  {
    slug: 'budgeting',
    type: 'budgeting',
    name: 'Budgeting',
    desc: 'Track department spend against budget targets and flag variance in real time.',
    capabilities: [
      'Budget creation with department-level line items and categories',
      'Weekly automated variance analysis — actual vs budget per line',
      'Configurable alert threshold for over-budget lines',
      'Critical overspend flagging with automatic approval routing',
      'AI-generated variance summary and cost reduction recommendations',
      'Multi-period budget support — create budgets per quarter or year',
      'Actual spend pulled from live expense and bill data',
    ],
  },
]

export function slugToTool(slug: string): ToolDef | undefined {
  return TOOLS.find((t) => t.slug === slug)
}
