import { dark } from '@clerk/themes'

export const clerkDarkAppearance = {
  baseTheme: dark,
  variables: {
    colorBackground: '#111111',
    colorText: '#f0f0f0',
    colorTextSecondary: '#a0a0a0',
    colorPrimary: '#00C853',
    colorTextOnPrimaryBackground: '#000000',
    colorInputBackground: '#1a1a1a',
    colorInputText: '#f0f0f0',
    colorNeutral: '#888888',
    borderRadius: '4px',
    fontSize: '14px',
  },
  elements: {
    rootBox: 'shadow-none',
    cardBox: 'bg-[#111111] border border-[#2c2c2c] shadow-none rounded-sm',
    card: 'bg-[#111111] shadow-none rounded-none',
    headerTitle: 'text-[#f0f0f0]',
    headerSubtitle: 'text-[#888888]',
    socialButtonsBlockButton: 'bg-[#1a1a1a] border border-[#2c2c2c] text-[#f0f0f0] hover:bg-[#222222]',
    socialButtonsBlockButtonText: 'text-[#f0f0f0] font-medium',
    dividerLine: 'bg-[#2c2c2c]',
    dividerText: 'text-[#555555]',
    formFieldLabel: 'text-[#a0a0a0]',
    formButtonPrimary: 'bg-[#00C853] text-black hover:bg-[#00a844]',
    footer: 'bg-[#0d0d0d] border-t border-[#2c2c2c]',
    footerAction: 'bg-[#0d0d0d]',
    footerActionText: 'text-[#666666]',
    footerActionLink: 'text-[#00C853] hover:text-[#00a844]',
  },
}

export const clerkLightAppearance = {
  variables: {
    colorBackground: '#ffffff',
    colorText: '#0d1117',
    colorTextSecondary: '#5d6b7a',
    colorPrimary: '#00C853',
    colorTextOnPrimaryBackground: '#000000',
    colorInputBackground: '#f5f5f5',
    colorInputText: '#0d1117',
    colorNeutral: '#3d4754',
    borderRadius: '4px',
    fontSize: '14px',
  },
  elements: {
    rootBox: 'shadow-none',
    cardBox: 'bg-white border border-[#e0e0e0] shadow-none rounded-sm',
    card: 'bg-white shadow-none rounded-none',
    headerTitle: 'text-[#0d1117]',
    headerSubtitle: 'text-[#5d6b7a]',
    socialButtonsBlockButton: 'bg-[#f5f5f5] border border-[#e0e0e0] text-[#0d1117] hover:bg-[#f4f6fb]',
    socialButtonsBlockButtonText: 'text-[#0d1117] font-medium',
    dividerLine: 'bg-[#e0e0e0]',
    dividerText: 'text-[#5d6b7a]',
    formFieldLabel: 'text-[#3d4754]',
    formButtonPrimary: 'bg-[#00C853] text-black hover:bg-[#00a844]',
    footer: 'bg-[#f4f6fb] border-t border-[#ebebeb]',
    footerAction: 'bg-[#f4f6fb]',
    footerActionText: 'text-[#5d6b7a]',
    footerActionLink: 'text-[#00C853] hover:text-[#00a844]',
  },
}
